# Generated by Django 4.1.5 on 2024-05-15 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id_langue', models.AutoField(primary_key=True, serialize=False)),
                ('nom_langue', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MotsFrancais',
            fields=[
                ('id_mots', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('image', models.FileField(null=True, upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Traduction',
            fields=[
                ('id_trad', models.AutoField(primary_key=True, serialize=False)),
                ('traduction', models.CharField(blank=True, max_length=255)),
                ('audio_traduction', models.FileField(max_length=255, upload_to='audio/')),
                ('expression', models.CharField(blank=True, max_length=255)),
                ('audio_expression', models.FileField(max_length=255, upload_to='audio/')),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dictionnaire.langue')),
                ('motsfrancais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dictionnaire.motsfrancais')),
            ],
        ),
    ]
